name: Build CV in PDF

on:
  push:
    branches:
      - master

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    container:
      image: texlive/texlive:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Git tag
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          git tag v1.0.${{ github.run_number }}
          git push origin v1.0.${{ github.run_number }}

      # Compile the file .tex
      - name: Compile LaTeX document
        run: |
          latexmk -pdf -interaction=nonstopmode -halt-on-error cv.tex
          mv cv.pdf CV_AFRV.pdf

      - name: Upload PDF to Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}
          files: CV_AFRV.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
